### ISSUE TITLE
Unclear what files are supposed to be used & merged to SWC

### ISSUE THREAD

**Issue by gavinsimpson** [karthik/bc#24]
It is not immediately clear what the structure of the bootcamp is, which files are main material and which are extraneous etc. For example, in `./R-basics` there are two apparently key `.Rmd` files with naming convention `00-title.Rmd` and `01-title.Rmd` etc, but the remaining `.Rmd` files don't follow this.

The `data-visualistion` folder contains a LaTeX source with R code as an `Rnw.` - is this part of the code that needs to be merged with SWC as part of the pull request? Do you want this reviewing too at this stage?

**Comment by jdblischak** [comment]
Perhaps you could provide a basic outline of a typical bootcamp, similar to your [schedule](https://github.com/swcarpentry/2013-10-09-canberra/blob/master/README.md) when you originally ran this bootcamp. But this time instead of linking to the rendered material, you could just list the names of the files to be taught. Not only will this help @gavinsimpson and me when reviewing the materials, but it will be invaluable to instructors that teach it.

**Comment by karthik** [comment]
Hi @gavinsimpson & @jdblischak,
Just realized a mistake of mine. I meant to hide the `md` files in the `gitignore` list but instead hid the `Rmd` files. This is why the repo appears so bare. Doh.  Just pushed so take a look. Here the files in order for each topic:

**Basic R**

01-basics-of-R.Rmd
02-data-structures.Rmd
03-best-practices.Rmd
04-seeking-help.Rmd
05-subsetting.Rmd
06-vectorization.Rmd

**Functions**

01-functions.Rmd
02-control_structures.Rmd
03-scoping_rules.Rmd

**Data Manipulation**

00-messy_data.Rmd
01-input-output.Rmd
02-apply-family.Rmd
03-split-apply.Rmd

**Data Visualization**

ggplot.R (the code tangled out)
ggplot.Rnw (the Rnw source for the PDF)
ggplot.pdf (Teach with this)
exercise.md

**Testing and Documentation**

documentation.md
testing.Rmd
exercise.md

**Reproducible Research**

knitr.Rmd
make.md
markdown.md

_Examples_
Makefile_1.txt
Makefile_2.txt
makefile_3.txt
exercise.md

**Comment by karthik** [comment]
Issue resolved. Closing.
