### ISSUE TITLE
R-basics/exercise.md.Rmd

### ISSUE THREAD

**Issue by jdblischak** [karthik/bc#28]
Is this supposed to be completed after lessons 01-basics-of-R and 02-data-structures? Exercises 2 and 3 deal with subsetting data frames, which has not yet been covered at this point. Similarly exercise 5 requires extracting info from a list using the name of the element (in the lesson you only retrieved information using the number of the element).

Then some minor issues:
- Is this a Markdown or RMarkdown file? It has both extensions, but is in Mardown format.
- The first line should be removed since those directions only apply to your past bootcamp.
- The numbering of the exercises is not preserved when converting to html.

**Comment by karthik** [comment]
This is just a markdown file to be completed at the end of all the lessons in this folder. It's simply `.md` (I'll fix this) because it makes no sense to have these as `Rmd`. All questions are of the type _please fix broken code_ so it wont execute anyway. Is there any good reason to have them as unevaluated code blocks?
